version: "3.7"
services:
  backend:
    build:
      context: ./api
    hostname: api
    restart: always
    container_name: api
    ports:
      - 7860:7860
    env_file:
      - .env
    volumes:
      - ./api:/api
  frontend:
    build:
      context: ./ui
    environment:
      - VITE_KG_CHAT_BACKEND_ENDPOINT=ws://kg-chat-backend:7860/text2text
    hostname: ui
    restart: always
    container_name: ui
    ports:
      - 4173:4173
