version: '3.7'
services:
  backend:
    build:
      context: backend/.
    hostname: kgchat-backend
    restart: always
    container_name: kgchat-backend
    ports:
      - 7860:7860
    env_file:
      - .env