# Use the official Python base image with the desired version
FROM python:3.11

# Create a shared folder
RUN mkdir -p /use_cases/shared

# Set the working directory
WORKDIR /use_cases/shared

COPY . /use_cases/shared
