version: "3.7"
services:
  backend:
    build:
      context: ../../
      dockerfile: ./use_cases/unstructured_data_import/Dockerfile
    hostname: unstructured-data-import-backend
    restart: always
    container_name: unstructured-data-import-backend
    ports:
      - 7860:7860
    env_file:
      - .env
    volumes:
      - .:/use_cases/unstructured_data_import
      - ../shared:/use_cases/shared
  frontend:
    build:
      context: ../../
      dockerfile: ./ui/Dockerfile
    environment:
      - VITE_UNSTRUCTUED_IMPORT_BACKEND_ENDPOINT=http://unstructured-data-import-backend:7860
    hostname: unstructured-data-import-frontend
    restart: always
    container_name: unstructured-data-import-frontend
    ports:
      - 4173:4173
